name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install build tools
        run: |
          pip install build setuptools_scm wheel

      - name: Update README with version
        run: |
          VERSION=$(python -c "from setuptools_scm import get_version; print(get_version())")
          sed -i "s/{{VERSION}}/$VERSION/g" README_TEMPLATE.md
          mv README_TEMPLATE.md README.md

      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
